/**
 * PeakRoutine — Master Ingredient Registry
 *
 * Every ingredient used in the meal database lives here with a stable ID.
 * Meal records reference these IDs — never raw strings.
 *
 * Design goals:
 *  • ~60 core ingredients that cover 95% of all meals
 *  • Every ingredient appears in at least 2–3 meals (high reuse)
 *  • Grocery categories match the grocery list screen's categories
 */

import { IngredientRecord } from '@/types/meal';

export const INGREDIENT_REGISTRY: IngredientRecord[] = [

  // ── PROTEIN ────────────────────────────────────────────────────────────────

  {
    id: 'eggs',
    name: 'Eggs',
    groceryCategory: 'protein',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: [],
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['chicken-thighs', 'turkey-mince'],
  },
  {
    id: 'chicken-thighs',
    name: 'Chicken Thighs',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['chicken-breast'],
  },
  {
    id: 'beef-mince',
    name: 'Lean Beef Mince',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['turkey-mince', 'chicken-breast'],
  },
  {
    id: 'turkey-mince',
    name: 'Turkey Mince',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['beef-mince'],
  },
  {
    id: 'sirloin-steak',
    name: 'Sirloin Steak',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['beef-mince'],
  },
  {
    id: 'salmon-fillet',
    name: 'Salmon Fillet',
    groceryCategory: 'protein',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['tuna-tinned'],
  },
  {
    id: 'tuna-tinned',
    name: 'Tinned Tuna (in spring water)',
    groceryCategory: 'protein',
    defaultUnit: 'can',
    shelfLife: 'pantry',
    commonSubstituteIds: ['salmon-fillet', 'chicken-breast'],
  },
  {
    id: 'whey-protein',
    name: 'Whey Protein Powder',
    groceryCategory: 'protein',
    defaultUnit: 'scoop',
    shelfLife: 'pantry',
    commonSubstituteIds: ['casein-protein'],
  },
  {
    id: 'casein-protein',
    name: 'Casein Protein Powder',
    groceryCategory: 'protein',
    defaultUnit: 'scoop',
    shelfLife: 'pantry',
    commonSubstituteIds: ['whey-protein'],
  },

  // ── DAIRY ──────────────────────────────────────────────────────────────────

  {
    id: 'milk',
    name: 'Full-Fat Milk',
    groceryCategory: 'dairy',
    defaultUnit: 'cup',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['oat-milk', 'almond-milk'],
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt',
    groceryCategory: 'dairy',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['cottage-cheese', 'skyr'],
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage Cheese',
    groceryCategory: 'dairy',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['greek-yogurt'],
  },
  {
    id: 'cheddar',
    name: 'Cheddar Cheese',
    groceryCategory: 'dairy',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['feta', 'parmesan'],
  },
  {
    id: 'feta',
    name: 'Feta Cheese',
    groceryCategory: 'dairy',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['cheddar'],
  },
  {
    id: 'parmesan',
    name: 'Parmesan',
    groceryCategory: 'dairy',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['cheddar'],
  },
  {
    id: 'sour-cream',
    name: 'Sour Cream',
    groceryCategory: 'dairy',
    defaultUnit: 'tbsp',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['greek-yogurt'],
  },
  {
    id: 'cream-cheese',
    name: 'Cream Cheese',
    groceryCategory: 'dairy',
    defaultUnit: 'tbsp',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['greek-yogurt', 'cottage-cheese'],
  },
  {
    id: 'butter',
    name: 'Butter',
    groceryCategory: 'dairy',
    defaultUnit: 'tbsp',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['olive-oil'],
  },
  {
    id: 'oat-milk',
    name: 'Oat Milk',
    groceryCategory: 'dairy',
    defaultUnit: 'cup',
    shelfLife: 'pantry',
    commonSubstituteIds: ['milk', 'almond-milk'],
  },

  // ── CARBS ──────────────────────────────────────────────────────────────────

  {
    id: 'brown-rice',
    name: 'Brown Rice',
    groceryCategory: 'carbs',
    defaultUnit: 'cup',
    shelfLife: 'pantry',
    commonSubstituteIds: ['quinoa', 'white-rice'],
  },
  {
    id: 'wholegrain-bread',
    name: 'Wholegrain Bread',
    groceryCategory: 'carbs',
    defaultUnit: 'slice',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['rye-bread', 'sourdough'],
  },
  {
    id: 'wholegrain-pasta',
    name: 'Wholegrain Pasta',
    groceryCategory: 'carbs',
    defaultUnit: 'g',
    shelfLife: 'pantry',
    commonSubstituteIds: ['brown-rice'],
  },
  {
    id: 'rolled-oats',
    name: 'Rolled Oats',
    groceryCategory: 'carbs',
    defaultUnit: 'cup',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    groceryCategory: 'carbs',
    defaultUnit: 'cup',
    shelfLife: 'pantry',
    commonSubstituteIds: ['brown-rice'],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    groceryCategory: 'carbs',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['baby-potatoes'],
  },
  {
    id: 'baby-potatoes',
    name: 'Baby Potatoes',
    groceryCategory: 'carbs',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['sweet-potato'],
  },
  {
    id: 'wholegrain-tortilla',
    name: 'Wholegrain Tortilla Wrap',
    groceryCategory: 'carbs',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['wholegrain-bread'],
  },
  {
    id: 'rice-cakes',
    name: 'Rice Cakes',
    groceryCategory: 'carbs',
    defaultUnit: 'piece',
    shelfLife: 'pantry',
    commonSubstituteIds: ['wholegrain-crackers'],
  },
  {
    id: 'wholegrain-crackers',
    name: 'Wholegrain Crackers',
    groceryCategory: 'carbs',
    defaultUnit: 'piece',
    shelfLife: 'pantry',
    commonSubstituteIds: ['rice-cakes'],
  },
  {
    id: 'granola',
    name: 'Granola',
    groceryCategory: 'carbs',
    defaultUnit: 'g',
    shelfLife: 'pantry',
    commonSubstituteIds: ['rolled-oats'],
  },

  // ── VEGETABLES ─────────────────────────────────────────────────────────────

  {
    id: 'broccoli',
    name: 'Broccoli',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['green-beans', 'asparagus'],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['mixed-leaves'],
  },
  {
    id: 'avocado',
    name: 'Avocado',
    groceryCategory: 'vegetables',
    defaultUnit: 'piece',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: [],
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    groceryCategory: 'vegetables',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['cherry-tomatoes', 'tinned-tomatoes'],
  },
  {
    id: 'cherry-tomatoes',
    name: 'Cherry Tomatoes',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['tomatoes'],
  },
  {
    id: 'tinned-tomatoes',
    name: 'Tinned Diced Tomatoes',
    groceryCategory: 'vegetables',
    defaultUnit: 'can',
    shelfLife: 'pantry',
    commonSubstituteIds: ['tomatoes'],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    groceryCategory: 'vegetables',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: [],
  },
  {
    id: 'capsicum',
    name: 'Capsicum (Bell Pepper)',
    groceryCategory: 'vegetables',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['zucchini'],
  },
  {
    id: 'green-beans',
    name: 'Green Beans',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['broccoli', 'asparagus'],
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['green-beans', 'broccoli'],
  },
  {
    id: 'mushrooms',
    name: 'Mushrooms',
    groceryCategory: 'vegetables',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['zucchini'],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    groceryCategory: 'vegetables',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['capsicum'],
  },

  // ── FRUIT ──────────────────────────────────────────────────────────────────

  {
    id: 'banana',
    name: 'Banana',
    groceryCategory: 'fruit',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['apple'],
  },
  {
    id: 'apple',
    name: 'Apple',
    groceryCategory: 'fruit',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['banana'],
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    groceryCategory: 'fruit',
    defaultUnit: 'g',
    shelfLife: 'fresh-3d',
    commonSubstituteIds: ['frozen-berries'],
  },
  {
    id: 'lemon',
    name: 'Lemon',
    groceryCategory: 'fruit',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['lime'],
  },
  {
    id: 'lime',
    name: 'Lime',
    groceryCategory: 'fruit',
    defaultUnit: 'piece',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['lemon'],
  },

  // ── FROZEN ─────────────────────────────────────────────────────────────────

  {
    id: 'frozen-berries',
    name: 'Frozen Mixed Berries',
    groceryCategory: 'frozen',
    defaultUnit: 'cup',
    shelfLife: 'frozen',
    commonSubstituteIds: ['strawberries'],
  },
  {
    id: 'frozen-mango',
    name: 'Frozen Mango Chunks',
    groceryCategory: 'frozen',
    defaultUnit: 'cup',
    shelfLife: 'frozen',
    commonSubstituteIds: ['banana'],
  },
  {
    id: 'frozen-peas-corn',
    name: 'Frozen Peas & Corn',
    groceryCategory: 'frozen',
    defaultUnit: 'cup',
    shelfLife: 'frozen',
    commonSubstituteIds: ['green-beans'],
  },

  // ── PANTRY ─────────────────────────────────────────────────────────────────

  {
    id: 'peanut-butter',
    name: 'Peanut Butter',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['almond-butter'],
  },
  {
    id: 'almond-butter',
    name: 'Almond Butter',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['peanut-butter'],
  },
  {
    id: 'mixed-nuts',
    name: 'Mixed Nuts',
    groceryCategory: 'pantry',
    defaultUnit: 'g',
    shelfLife: 'pantry',
    commonSubstituteIds: ['almonds'],
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate (70%+)',
    groceryCategory: 'pantry',
    defaultUnit: 'g',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'chia-seeds',
    name: 'Chia Seeds',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'honey',
    name: 'Honey',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['maple-syrup'],
  },
  {
    id: 'maple-syrup',
    name: 'Maple Syrup',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['honey'],
  },
  {
    id: 'soy-sauce',
    name: 'Soy Sauce',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'sesame-oil',
    name: 'Sesame Oil',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['olive-oil'],
  },
  {
    id: 'olive-oil',
    name: 'Olive Oil',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'pantry',
    commonSubstituteIds: ['sesame-oil'],
  },
  {
    id: 'hummus',
    name: 'Hummus',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['cream-cheese'],
  },
  {
    id: 'salsa',
    name: 'Salsa',
    groceryCategory: 'pantry',
    defaultUnit: 'tbsp',
    shelfLife: 'fresh-7d',
    commonSubstituteIds: ['tinned-tomatoes'],
  },
  {
    id: 'cinnamon',
    name: 'Cinnamon',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'ginger',
    name: 'Fresh or Ground Ginger',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },
  {
    id: 'cacao-powder',
    name: 'Cacao Powder',
    groceryCategory: 'pantry',
    defaultUnit: 'tsp',
    shelfLife: 'pantry',
    commonSubstituteIds: [],
  },

  // ── DRINKS ─────────────────────────────────────────────────────────────────

  {
    id: 'coconut-water',
    name: 'Coconut Water',
    groceryCategory: 'drinks',
    defaultUnit: 'cup',
    shelfLife: 'pantry',
    commonSubstituteIds: ['milk', 'oat-milk'],
  },
];

// ─── Quick lookup helper ───────────────────────────────────────────────────────

const _registryMap = new Map(INGREDIENT_REGISTRY.map(i => [i.id, i]));

export function getIngredient(id: string): IngredientRecord | undefined {
  return _registryMap.get(id);
}
