export interface ShakeRecipe {
  id: string;
  name: string;
  emoji: string;
  timing: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  color: string;
  ingredients: string[];
  instructions: string;
  tip: string;
}

export interface Meal {
  id: string;
  name: string;
  emoji: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  timing: string;
  category: 'pre-workout' | 'post-workout' | 'main' | 'snack' | 'night-shift';
  description: string;
  ingredients: string[];
  tip?: string;
}

export const SHAKE_RECIPES: ShakeRecipe[] = [
  {
    id: 'recovery',
    name: 'Post-Workout Recovery',
    emoji: '💪',
    timing: 'Within 30 min after gym',
    calories: 420,
    protein: 38,
    carbs: 45,
    fat: 9,
    color: '#a855f7',
    ingredients: [
      '1 scoop whey protein (chocolate or vanilla)',
      '1 cup full-fat milk',
      '1 ripe banana',
      '1 tbsp peanut butter',
      'Handful of ice cubes',
    ],
    instructions: 'Blend all ingredients until smooth. Drink immediately. Add a splash of water if too thick.',
    tip: 'Add creatine (5g) directly to this shake — you won\'t taste it.',
  },
  {
    id: 'bedtime',
    name: 'Pre-Sleep Casein',
    emoji: '🌙',
    timing: 'Before sleep (9 AM)',
    calories: 220,
    protein: 28,
    carbs: 18,
    fat: 3,
    color: '#6366f1',
    ingredients: [
      '1 scoop casein protein (vanilla or unflavoured)',
      '1 cup warm full-fat milk',
      '1 tsp raw honey',
      '½ tsp cinnamon',
      'Pinch of nutmeg (optional)',
    ],
    instructions: 'Warm the milk slightly (not boiling). Stir in casein until dissolved. Add honey and spices. Drink slowly.',
    tip: 'Casein digests slowly over 6–8 hours, feeding your muscles throughout sleep. Perfect for your 7.5-hr rest window.',
  },
  {
    id: 'nightshift',
    name: 'Night Shift Energy',
    emoji: '⚡',
    timing: 'During work shift (2–3 AM)',
    calories: 460,
    protein: 30,
    carbs: 58,
    fat: 12,
    color: '#f59e0b',
    ingredients: [
      '1 scoop whey protein (any flavour)',
      '1 cup full-fat milk',
      '½ cup rolled oats',
      '1 tbsp peanut butter',
      '1 tsp cacao powder',
      '½ tsp vanilla extract',
      'Ice cubes',
    ],
    instructions: 'Blend all ingredients. The oats give slow-release energy perfect for the 2–4 AM slump.',
    tip: 'Blend oats lightly — don\'t over-blend or it gets too thick. Add extra milk if needed.',
  },
  {
    id: 'green',
    name: 'Mango Ginger Boost',
    emoji: '🥭',
    timing: 'After Tuesday/Wednesday gym',
    calories: 360,
    protein: 29,
    carbs: 56,
    fat: 4,
    color: '#22c55e',
    ingredients: [
      '1 scoop vanilla whey protein',
      '1 cup frozen mango chunks',
      '1 banana',
      '1 cup coconut water',
      '½ tsp fresh or frozen ginger',
      'Juice of ½ lime',
    ],
    instructions: 'Blend all ingredients until smooth. Add more coconut water if too thick.',
    tip: 'Mango and coconut water replenish electrolytes post-workout. Ginger reduces muscle soreness.',
  },
  {
    id: 'warmcasein',
    name: 'Warm Bedtime Milk',
    emoji: '☕',
    timing: 'Pre-sleep wind-down',
    calories: 200,
    protein: 25,
    carbs: 15,
    fat: 3,
    color: '#d97706',
    ingredients: [
      '1 scoop casein protein',
      '250ml warm full-fat milk',
      '1 tsp honey',
      '1 tsp cinnamon',
      '¼ tsp vanilla extract',
    ],
    instructions: 'Warm milk until steaming (not boiling). Whisk in casein until smooth. Add honey and cinnamon.',
    tip: 'Drinking something warm signals to your body it\'s time to sleep — great for resetting before 9 AM sleep.',
  },
  {
    id: 'fruity',
    name: 'Berry Burst',
    emoji: '🫐',
    timing: 'Anytime / post-workout',
    calories: 320,
    protein: 30,
    carbs: 42,
    fat: 3,
    color: '#ec4899',
    ingredients: [
      '1 scoop vanilla or strawberry whey protein',
      '1 cup frozen mixed berries (blueberries, raspberries, strawberries)',
      '1 cup low-fat Greek yogurt',
      '½ cup full-fat milk',
      '1 tsp honey',
    ],
    instructions: 'Blend everything together. The Greek yogurt adds extra protein and creates a thick, creamy texture.',
    tip: 'Berries are packed with antioxidants that help reduce post-workout inflammation. Great on non-gym days too.',
  },
];

export const MEAL_IDEAS: Meal[] = [
  {
    id: 'chicken-rice',
    name: 'Chicken Rice Bowl',
    emoji: '🍚',
    calories: 480,
    protein: 42,
    carbs: 54,
    fat: 8,
    timing: 'Pre-class / Meal 1',
    category: 'pre-workout',
    description: 'A classic high-protein meal that\'s easy to batch cook on Sundays.',
    ingredients: [
      '120g grilled chicken breast',
      '½ cup brown rice (dry, cooked)',
      '½ cup frozen peas',
      '½ cup frozen corn',
      'Soy sauce + sesame oil drizzle',
    ],
    tip: 'Batch cook chicken and rice on Sundays. Add frozen peas and corn straight from frozen — they defrost in seconds with hot rice.',
  },
  {
    id: 'salmon-quinoa',
    name: 'Chicken & Quinoa Bowl',
    emoji: '🥗',
    calories: 500,
    protein: 43,
    carbs: 50,
    fat: 10,
    timing: 'Post-workout dinner',
    category: 'post-workout',
    description: 'Quinoa is a complete protein — paired with chicken it\'s ideal for muscle recovery.',
    ingredients: [
      '150g grilled chicken breast',
      '1 cup cooked quinoa',
      '½ cup frozen peas',
      '1 carrot (grated or diced)',
      'Lemon juice + olive oil + garlic',
    ],
    tip: 'Cook a big batch of quinoa at the start of the week. It keeps in the fridge for 5 days.',
  },
  {
    id: 'egg-avo-toast',
    name: 'Eggs & Avo Toast',
    emoji: '🥑',
    calories: 430,
    protein: 26,
    carbs: 34,
    fat: 22,
    timing: 'Wake-up meal / Meal 1',
    category: 'main',
    description: 'Quick, satisfying and full of healthy fats and protein.',
    ingredients: [
      '2 eggs (poached or fried)',
      '2 slices wholegrain sourdough',
      '½ ripe avocado',
      '1 tomato (sliced)',
      'Salt, pepper, chilli flakes',
    ],
  },
  {
    id: 'turkey-stir',
    name: 'Beef Mince Fried Rice',
    emoji: '🍳',
    calories: 540,
    protein: 40,
    carbs: 54,
    fat: 15,
    timing: 'Post-workout dinner',
    category: 'post-workout',
    description: 'One-pan meal ready in 15 minutes. Using leftover rice makes this even faster.',
    ingredients: [
      '150g lean beef mince',
      '1 cup cooked rice',
      '½ cup frozen peas + corn mix',
      '1 egg',
      '2 tbsp soy sauce',
      'Garlic + dash of sesame oil',
    ],
    tip: 'Cook extra rice and freeze in portions — this comes together in 10 minutes with pre-cooked rice.',
  },
  {
    id: 'taco-bowl',
    name: 'Beef Taco Bowl',
    emoji: '🌮',
    calories: 560,
    protein: 44,
    carbs: 52,
    fat: 14,
    timing: 'Thursday dinner',
    category: 'main',
    description: 'Satisfying and macro-friendly. Everything keeps well in the fridge for next-day leftovers.',
    ingredients: [
      '150g lean beef mince',
      '½ cup brown rice (cooked)',
      '½ cup frozen corn',
      '½ cup tinned diced tomatoes',
      '2 tbsp sour cream',
      'Grated cheddar + jalapeños (optional)',
    ],
    tip: 'Season the beef with cumin, garlic powder and paprika for an easy taco flavour without any kits.',
  },
  {
    id: 'overnight-oats',
    name: 'Overnight Protein Oats',
    emoji: '🥣',
    calories: 380,
    protein: 28,
    carbs: 52,
    fat: 7,
    timing: 'Any meal / night shift snack',
    category: 'night-shift',
    description: 'Prep the night before — perfect for night shift snacking at 4 AM.',
    ingredients: [
      '½ cup rolled oats',
      '1 scoop protein powder (vanilla)',
      '¾ cup full-fat milk',
      '1 tbsp chia seeds',
      'Frozen berries + drizzle honey',
    ],
    tip: 'Mix all ingredients in a jar before your shift starts. It\'ll be perfectly soaked by the time you eat at 4 AM.',
  },
  {
    id: 'tuna-wrap',
    name: 'Chicken Salsa Wrap',
    emoji: '🫔',
    calories: 420,
    protein: 38,
    carbs: 36,
    fat: 10,
    timing: 'Night shift meal',
    category: 'night-shift',
    description: 'Easy to prep and eat at your desk. Fill it, roll it, done.',
    ingredients: [
      '1 wholegrain tortilla',
      '120g cooked chicken breast (sliced or shredded)',
      '3 tbsp salsa or tinned diced tomatoes',
      '1 tbsp sour cream',
      'Grated cheddar',
    ],
    tip: 'Pre-cook and shred a batch of chicken on Sunday. Wraps take 2 minutes to assemble during your shift.',
  },
  {
    id: 'steak-potatoes',
    name: 'Saturday Steak Night',
    emoji: '🥩',
    calories: 600,
    protein: 48,
    carbs: 44,
    fat: 18,
    timing: 'Saturday post-workout dinner',
    category: 'post-workout',
    description: 'Treat yourself after a big full-body session. Red meat is packed with iron and zinc.',
    ingredients: [
      '150g sirloin steak',
      'Roasted baby potatoes (200g)',
      '½ cup peas (steamed or microwaved from frozen)',
      'Peppercorn sauce or butter + garlic',
    ],
    tip: 'Pat the steak dry before cooking for a better sear. Let it rest 2–3 minutes after cooking.',
  },
  {
    id: 'sunday-pasta',
    name: 'Sunday Beef Pasta',
    emoji: '🍝',
    calories: 580,
    protein: 40,
    carbs: 70,
    fat: 11,
    timing: 'Sunday dinner',
    category: 'main',
    description: 'Higher carbs on rest day to replenish glycogen for the week ahead.',
    ingredients: [
      '100g wholegrain pasta (dry)',
      '150g lean beef mince',
      '1 tin (400g) diced tomatoes',
      'Garlic + Italian herbs (dried)',
      'Parmesan to serve',
    ],
    tip: 'Make double and refrigerate — reheats perfectly for a night shift meal the next day.',
  },
  {
    id: 'scrambled-salmon',
    name: 'Cheesy Scrambled Eggs',
    emoji: '🍳',
    calories: 460,
    protein: 28,
    carbs: 30,
    fat: 24,
    timing: 'Wake-up meal / Sunday brunch',
    category: 'main',
    description: 'Creamy scrambled eggs on toast — ready in under 5 minutes, high in protein.',
    ingredients: [
      '3 large eggs',
      '2 tbsp full-fat milk',
      '20g grated cheddar',
      '2 slices wholegrain toast',
      '1 tomato (sliced)',
      'Butter + salt + pepper',
    ],
    tip: 'Low and slow on the heat makes the creamiest scrambled eggs. Pull off heat just before fully set — residual heat finishes them.',
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage Cheese Bowl',
    emoji: '🧀',
    calories: 200,
    protein: 22,
    carbs: 18,
    fat: 3,
    timing: 'Snack / pre-sleep',
    category: 'snack',
    description: 'High in casein protein — perfect as a pre-sleep snack.',
    ingredients: [
      '150g low-fat cottage cheese',
      'Sliced strawberries or tinned peach',
      '1 tbsp chia seeds',
      'Drizzle of honey',
      'Pinch of cinnamon',
    ],
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt Parfait',
    emoji: '🫙',
    calories: 310,
    protein: 24,
    carbs: 38,
    fat: 6,
    timing: 'Snack / morning',
    category: 'snack',
    description: 'Quick, no-cook snack that packs a protein punch.',
    ingredients: [
      '200g full-fat Greek yogurt',
      '30g granola',
      'Handful frozen berries (defrosted)',
      '1 tsp honey',
      '1 tbsp chia seeds',
    ],
  },
];

export const MACRO_TARGETS = {
  calories: 1900,
  protein: 145,
  carbs: 200,
  fat: 65,
  water: 2500, // ml
  note: 'Targets are approximate for a 30F toning goal at moderate activity level. Adjust based on hunger and progress.',
};
