export interface ShakeRecipe {
  id: string;
  name: string;
  emoji: string;
  timing: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  color: string;
  ingredients: string[];
  instructions: string;
  tip: string;
}

export interface Meal {
  id: string;
  name: string;
  emoji: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  timing: string;
  category: 'pre-workout' | 'post-workout' | 'main' | 'snack' | 'night-shift';
  description: string;
  ingredients: string[];
  instructions: string;
  tip?: string;
}

export const SHAKE_RECIPES: ShakeRecipe[] = [
  {
    id: 'recovery',
    name: 'Post-Workout Recovery',
    emoji: '💪',
    timing: 'Within 30 min after gym',
    calories: 420,
    protein: 38,
    carbs: 45,
    fat: 9,
    color: '#a855f7',
    ingredients: [
      '1 scoop whey protein (chocolate or vanilla)',
      '1 cup full-fat milk',
      '1 ripe banana',
      '1 tbsp peanut butter',
      'Handful of ice cubes',
    ],
    instructions: 'Blend all ingredients until smooth. Drink immediately. Add a splash of water if too thick.',
    tip: 'Add creatine (5g) directly to this shake — you won\'t taste it.',
  },
  {
    id: 'bedtime',
    name: 'Pre-Sleep Casein',
    emoji: '🌙',
    timing: 'Before sleep (9 AM)',
    calories: 220,
    protein: 28,
    carbs: 18,
    fat: 3,
    color: '#6366f1',
    ingredients: [
      '1 scoop casein protein (vanilla or unflavoured)',
      '1 cup warm full-fat milk',
      '1 tsp raw honey',
      '½ tsp cinnamon',
      'Pinch of nutmeg (optional)',
    ],
    instructions: 'Warm the milk slightly (not boiling). Stir in casein until dissolved. Add honey and spices. Drink slowly.',
    tip: 'Casein digests slowly over 6–8 hours, feeding your muscles throughout sleep. Perfect for your 7.5-hr rest window.',
  },
  {
    id: 'nightshift',
    name: 'Night Shift Energy',
    emoji: '⚡',
    timing: 'During work shift (2–3 AM)',
    calories: 460,
    protein: 30,
    carbs: 58,
    fat: 12,
    color: '#f59e0b',
    ingredients: [
      '1 scoop whey protein (any flavour)',
      '1 cup full-fat milk',
      '½ cup rolled oats',
      '1 tbsp peanut butter',
      '1 tsp cacao powder',
      '½ tsp vanilla extract',
      'Ice cubes',
    ],
    instructions: 'Blend all ingredients. The oats give slow-release energy perfect for the 2–4 AM slump.',
    tip: 'Blend oats lightly — don\'t over-blend or it gets too thick. Add extra milk if needed.',
  },
  {
    id: 'green',
    name: 'Mango Ginger Boost',
    emoji: '🥭',
    timing: 'After Tuesday/Wednesday gym',
    calories: 360,
    protein: 29,
    carbs: 56,
    fat: 4,
    color: '#22c55e',
    ingredients: [
      '1 scoop vanilla whey protein',
      '1 cup frozen mango chunks',
      '1 banana',
      '1 cup coconut water',
      '½ tsp fresh or frozen ginger',
      'Juice of ½ lime',
    ],
    instructions: 'Blend all ingredients until smooth. Add more coconut water if too thick.',
    tip: 'Mango and coconut water replenish electrolytes post-workout. Ginger reduces muscle soreness.',
  },
  {
    id: 'warmcasein',
    name: 'Warm Bedtime Milk',
    emoji: '☕',
    timing: 'Pre-sleep wind-down',
    calories: 200,
    protein: 25,
    carbs: 15,
    fat: 3,
    color: '#d97706',
    ingredients: [
      '1 scoop casein protein',
      '250ml warm full-fat milk',
      '1 tsp honey',
      '1 tsp cinnamon',
      '¼ tsp vanilla extract',
    ],
    instructions: 'Warm milk until steaming (not boiling). Whisk in casein until smooth. Add honey and cinnamon.',
    tip: 'Drinking something warm signals to your body it\'s time to sleep — great for resetting before 9 AM sleep.',
  },
  {
    id: 'fruity',
    name: 'Berry Burst',
    emoji: '🫐',
    timing: 'Anytime / post-workout',
    calories: 320,
    protein: 30,
    carbs: 42,
    fat: 3,
    color: '#ec4899',
    ingredients: [
      '1 scoop vanilla or strawberry whey protein',
      '1 cup frozen mixed berries (blueberries, raspberries, strawberries)',
      '1 cup low-fat Greek yogurt',
      '½ cup full-fat milk',
      '1 tsp honey',
    ],
    instructions: 'Blend everything together. The Greek yogurt adds extra protein and creates a thick, creamy texture.',
    tip: 'Berries are packed with antioxidants that help reduce post-workout inflammation. Great on non-gym days too.',
  },
];

export const MEAL_IDEAS: Meal[] = [
  {
    id: 'chicken-rice',
    name: 'Chicken Rice Bowl',
    emoji: '🍚',
    calories: 480,
    protein: 42,
    carbs: 54,
    fat: 8,
    timing: 'Pre-class / Meal 1',
    category: 'pre-workout',
    description: 'A classic high-protein meal that\'s easy to batch cook on Sundays.',
    ingredients: [
      '120g grilled chicken breast',
      '½ cup brown rice (dry, cooked)',
      '½ cup frozen peas',
      '½ cup frozen corn',
      'Soy sauce + sesame oil drizzle',
    ],
    instructions: 'Cook rice in 2× water, covered, ~15 min or until absorbed. Season chicken and grill or pan-fry over medium-high heat 5–6 min per side until cooked through — slice across the grain. Microwave peas and corn 2 min. Serve chicken over rice, top with veg, drizzle soy sauce and a few drops of sesame oil.',
    tip: 'Batch cook chicken and rice on Sundays. Add frozen peas and corn straight from frozen — they defrost in seconds with hot rice.',
  },
  {
    id: 'salmon-quinoa',
    name: 'Salmon & Quinoa Bowl',
    emoji: '🐟',
    calories: 520,
    protein: 42,
    carbs: 46,
    fat: 14,
    timing: 'Post-workout dinner',
    category: 'post-workout',
    description: 'Omega-3 rich salmon paired with protein-complete quinoa — ideal for muscle recovery after leg day.',
    ingredients: [
      '150g salmon fillet',
      '1 cup cooked quinoa',
      '1 cup broccoli florets',
      'Lemon juice + olive oil',
      'Garlic + black pepper',
    ],
    instructions: 'Rinse quinoa and cook in 2× water for 12 min until absorbed. Season salmon with salt, pepper and lemon. Pan-fry skin-side down in a hot pan 4–5 min, flip and cook 2–3 min more, or bake at 200°C for 12–15 min until it flakes easily. Steam or microwave broccoli 4 min. Dress everything with lemon juice, olive oil and minced garlic.',
    tip: 'Salmon is packed with omega-3s — perfect for reducing post-workout inflammation after leg day. Don\'t overcook it; it\'s done when it flakes with a fork.',
  },
  {
    id: 'egg-avo-toast',
    name: 'Eggs & Avo Toast',
    emoji: '🥑',
    calories: 430,
    protein: 26,
    carbs: 34,
    fat: 22,
    timing: 'Wake-up meal / Meal 1',
    category: 'main',
    description: 'Quick, satisfying and full of healthy fats and protein.',
    ingredients: [
      '2 eggs (poached or fried)',
      '2 slices wholegrain sourdough',
      '½ ripe avocado',
      '1 tomato (sliced)',
      'Salt, pepper, chilli flakes',
    ],
    instructions: 'Toast bread until golden. To poach: bring a pan of water to a gentle simmer with a splash of vinegar, swirl, slide in cracked eggs, cook 3 min. To fry: heat butter over medium heat, fry to your liking. Mash avocado with lemon juice, salt and pepper. Spread on toast, top with egg, sliced tomato and chilli flakes.',
  },
  {
    id: 'turkey-stir',
    name: 'Turkey Mince Stir-Fry',
    emoji: '🥢',
    calories: 500,
    protein: 40,
    carbs: 48,
    fat: 12,
    timing: 'Post-workout dinner',
    category: 'post-workout',
    description: 'One-pan meal ready in 15 minutes. High-protein, macro-friendly and great with batch-cooked rice.',
    ingredients: [
      '150g turkey mince (or lean beef mince)',
      '1 cup cooked brown rice',
      '1 cup mixed capsicum, snap peas and bok choy',
      '1 egg',
      '2 tbsp soy sauce',
      '1 tsp sesame oil + minced garlic',
    ],
    instructions: 'Heat a wok or large pan over high heat with a splash of oil. Add mince and cook 5–6 min, breaking it up until browned. Push to one side, crack in egg and scramble quickly. Add cooked rice and vegetables. Toss everything together with soy sauce, minced garlic and a drizzle of sesame oil. Stir-fry on high heat 2–3 min until piping hot.',
    tip: 'Prep all the veg in advance — once the pan is hot this comes together in under 10 minutes. Turkey mince is leaner than beef with just as much protein.',
  },
  {
    id: 'taco-bowl',
    name: 'Beef Taco Bowl',
    emoji: '🌮',
    calories: 560,
    protein: 44,
    carbs: 52,
    fat: 14,
    timing: 'Thursday dinner',
    category: 'main',
    description: 'Satisfying and macro-friendly. Everything keeps well in the fridge for next-day leftovers.',
    ingredients: [
      '150g lean beef mince',
      '½ cup brown rice (cooked)',
      '½ cup frozen corn',
      '½ cup tinned diced tomatoes',
      '2 tbsp sour cream',
      'Grated cheddar + jalapeños (optional)',
    ],
    instructions: 'Brown beef mince in a pan over medium-high heat 5–6 min, breaking it up. Season with cumin, garlic powder, paprika, salt and pepper. Add tinned tomatoes and frozen corn, simmer 3–4 min until thickened. Serve over cooked rice. Top with sour cream, grated cheddar and jalapeños.',
    tip: 'Season the beef with cumin, garlic powder and paprika for an easy taco flavour without any kits.',
  },
  {
    id: 'overnight-oats',
    name: 'Overnight Protein Oats',
    emoji: '🥣',
    calories: 380,
    protein: 28,
    carbs: 52,
    fat: 7,
    timing: 'Any meal / night shift snack',
    category: 'night-shift',
    description: 'Prep the night before — perfect for night shift snacking at 4 AM.',
    ingredients: [
      '½ cup rolled oats',
      '1 scoop protein powder (vanilla)',
      '¾ cup full-fat milk',
      '1 tbsp chia seeds',
      'Frozen berries + drizzle honey',
    ],
    instructions: 'Add oats, protein powder, chia seeds and milk to a jar. Stir well until the protein powder is fully mixed in — no lumps. Cover and refrigerate overnight or minimum 4 hours. Before eating, top with defrosted berries and a drizzle of honey. Eat cold straight from the jar.',
    tip: 'Mix all ingredients in a jar before your shift starts. It\'ll be perfectly soaked by the time you eat at 4 AM.',
  },
  {
    id: 'tuna-wrap',
    name: 'Tuna Cream Cheese Wrap',
    emoji: '🫔',
    calories: 380,
    protein: 36,
    carbs: 36,
    fat: 9,
    timing: 'Night shift meal',
    category: 'night-shift',
    description: 'Easy to prep and eat at your desk. No cooking needed.',
    ingredients: [
      '1 wholegrain tortilla wrap',
      '150g tinned tuna in spring water',
      '2 tbsp cream cheese',
      '½ cucumber (sliced)',
      'Handful spinach leaves',
      'Squeeze of lemon',
    ],
    instructions: 'Drain tuna thoroughly and place in a bowl. Mix with cream cheese, lemon juice, salt and pepper. Lay wrap flat. Spread tuna mixture across the centre third. Add cucumber slices and spinach leaves. Fold in the sides, then roll tightly from the bottom. Slice in half on the diagonal. No cooking needed.',
    tip: 'Drain tuna well before mixing with cream cheese. Wraps take 2 minutes to assemble during your shift.',
  },
  {
    id: 'tuna-crackers',
    name: 'Tuna & Cracker Plate',
    emoji: '🐟',
    calories: 360,
    protein: 35,
    carbs: 28,
    fat: 7,
    timing: 'Night shift meal',
    category: 'night-shift',
    description: 'No-cook high-protein plate — quick to prep, easy to eat at the desk.',
    ingredients: [
      '150g tinned tuna in spring water',
      '10 wholegrain crackers',
      '½ cucumber (sliced)',
      '2 tbsp hummus',
      'Squeeze of lemon',
    ],
    instructions: 'Drain tuna and season with lemon juice, salt and pepper. Slice cucumber. Arrange crackers on a plate. Place tuna on top of crackers or in a small bowl for dipping. Serve hummus alongside the cucumber for dipping. No cooking required — just open and assemble.',
    tip: 'Keep a few tins of tuna and a box of crackers at your desk so this is always an option.',
  },
  {
    id: 'steak-potatoes',
    name: 'Saturday Steak Night',
    emoji: '🥩',
    calories: 600,
    protein: 48,
    carbs: 44,
    fat: 18,
    timing: 'Saturday post-workout dinner',
    category: 'post-workout',
    description: 'Treat yourself after a big full-body session. Red meat is packed with iron and zinc.',
    ingredients: [
      '150g sirloin steak',
      'Roasted baby potatoes (200g)',
      '½ cup peas (steamed or microwaved from frozen)',
      'Peppercorn sauce or butter + garlic',
    ],
    instructions: 'Preheat oven to 200°C. Halve baby potatoes, toss in olive oil, salt and pepper — roast 25–30 min until golden. Bring steak to room temp 15 min before cooking. Heat a heavy pan until very hot. Pat steak completely dry, season generously. Sear 2–3 min per side for medium. Add a knob of butter and a crushed garlic clove, baste 30 sec. Rest 3 min before slicing. Microwave peas 2 min.',
    tip: 'Pat the steak dry before cooking for a better sear. Let it rest 2–3 minutes after cooking.',
  },
  {
    id: 'sunday-pasta',
    name: 'Sunday Beef Pasta',
    emoji: '🍝',
    calories: 580,
    protein: 40,
    carbs: 70,
    fat: 11,
    timing: 'Sunday dinner',
    category: 'main',
    description: 'Higher carbs on rest day to replenish glycogen for the week ahead.',
    ingredients: [
      '100g wholegrain pasta (dry)',
      '150g lean beef mince',
      '1 tin (400g) diced tomatoes',
      'Garlic + Italian herbs (dried)',
      'Parmesan to serve',
    ],
    instructions: 'Boil pasta in well-salted water to packet instructions (~10–12 min). Meanwhile, brown mince in a pan over medium-high heat, drain excess fat. Add minced garlic, cook 1 min. Pour in tinned tomatoes, add a big pinch of dried Italian herbs, salt and pepper. Simmer 8–10 min until thickened. Drain pasta, combine with sauce. Finish with a generous grating of parmesan.',
    tip: 'Make double and refrigerate — reheats perfectly for a night shift meal the next day.',
  },
  {
    id: 'scrambled-salmon',
    name: 'Smoked Salmon Scramble',
    emoji: '🥚',
    calories: 520,
    protein: 38,
    carbs: 32,
    fat: 26,
    timing: 'Sunday brunch',
    category: 'main',
    description: 'A proper Sunday brunch — silky scrambled eggs, smoked salmon, avocado on rye. Worth every calorie.',
    ingredients: [
      '3 large eggs',
      '80g smoked salmon',
      '2 slices rye bread',
      '½ ripe avocado',
      'Handful spinach (optional, wilted)',
      'Butter + salt + pepper + lemon',
    ],
    instructions: 'Toast rye bread. Whisk eggs with salt and pepper. Melt a knob of butter in a non-stick pan over low–medium heat. Pour in eggs and fold very gently with a spatula — keep them moving. Remove from heat while still softly set and glossy. Mash avocado with a squeeze of lemon, salt and pepper. Optional: briefly wilt spinach in the same pan before the eggs. Serve eggs on rye toast, layer smoked salmon on top, finish with avocado.',
    tip: 'Low and slow is everything — pull eggs off heat while still slightly wet. Residual heat finishes them perfectly. Don\'t rush it.',
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage Cheese Bowl',
    emoji: '🧀',
    calories: 200,
    protein: 22,
    carbs: 18,
    fat: 3,
    timing: 'Snack / pre-sleep',
    category: 'snack',
    description: 'High in casein protein — perfect as a pre-sleep snack.',
    ingredients: [
      '150g low-fat cottage cheese',
      'Sliced strawberries or tinned peach',
      '1 tbsp chia seeds',
      'Drizzle of honey',
      'Pinch of cinnamon',
    ],
    instructions: 'No cooking needed. Spoon cottage cheese into a bowl. Slice fresh strawberries or drain tinned peach slices and arrange on top. Sprinkle over chia seeds and cinnamon. Drizzle honey over the top. Ready in under 2 minutes.',
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt Parfait',
    emoji: '🫙',
    calories: 310,
    protein: 24,
    carbs: 38,
    fat: 6,
    timing: 'Snack / morning',
    category: 'snack',
    description: 'Quick, no-cook snack that packs a protein punch.',
    ingredients: [
      '200g full-fat Greek yogurt',
      '30g granola',
      'Handful frozen berries (defrosted)',
      '1 tsp honey',
      '1 tbsp chia seeds',
    ],
    instructions: 'No cooking needed. Defrost berries by leaving at room temp 5 min or microwaving 30 sec. Spoon yogurt into a bowl or glass. Add granola, then the berries. Drizzle honey and sprinkle chia seeds. Layer it for extra texture — yogurt, granola, berries, repeat. Ready in 2 minutes.',
  },
  {
    id: 'baked-chicken-thighs',
    name: 'Baked Chicken Thighs',
    emoji: '🍗',
    calories: 550,
    protein: 40,
    carbs: 42,
    fat: 16,
    timing: 'Rest day dinner',
    category: 'main',
    description: 'Juicy golden chicken thighs with roasted sweet potato and garlic butter green beans — the rest day reward meal.',
    ingredients: [
      '2 bone-in chicken thighs (skin-on)',
      '1 medium sweet potato',
      '100g green beans',
      '2 cloves garlic + 1 tbsp butter',
      'Olive oil + smoked paprika + salt + pepper',
    ],
    instructions: 'Preheat oven to 200°C. Cut sweet potato into wedges, toss in olive oil, smoked paprika, salt and pepper — spread on a tray. Pat chicken skin completely dry, season generously. Place skin-side up on the same or separate tray. Roast 35–40 min until skin is deeply golden and juices run clear. Last 5 min: blanch green beans in boiling water 3 min, drain and toss in a pan with butter and minced garlic for 1–2 min.',
    tip: 'Patting the skin dry is the key to getting it crispy. Chicken thighs are forgiving — they stay juicy even if slightly overcooked.',
  },
  {
    id: 'smoothie-bowl',
    name: 'Protein Smoothie Bowl',
    emoji: '🍓',
    calories: 450,
    protein: 32,
    carbs: 58,
    fat: 8,
    timing: 'Pre-workout Meal 1',
    category: 'pre-workout',
    description: 'Tastes like dessert, fuels like a proper meal. The frozen banana makes it thick and naturally sweet.',
    ingredients: [
      '1 scoop vanilla protein powder',
      '1 frozen banana',
      '¾ cup full-fat milk',
      '30g granola',
      'Sliced strawberries + handful blueberries',
      '1 tsp honey + 1 tsp chia seeds',
    ],
    instructions: 'Blend protein powder, frozen banana and milk until thick and smooth. Use less liquid than a regular shake — it should be thick enough to eat with a spoon. Pour into a bowl. Top with granola, sliced strawberries, blueberries, a drizzle of honey and a sprinkle of chia seeds.',
    tip: 'The secret is less liquid. Use the frozen banana straight from the freezer — it creates a naturally cold, creamy ice-cream texture.',
  },
  {
    id: 'sweet-potato-eggs',
    name: 'Sweet Potato & Eggs',
    emoji: '🍠',
    calories: 400,
    protein: 22,
    carbs: 48,
    fat: 12,
    timing: 'Night shift meal',
    category: 'night-shift',
    description: 'Complex carbs from sweet potato with protein-rich boiled eggs. Steady energy to get through 4–8 AM.',
    ingredients: [
      '1 medium sweet potato',
      '2 large eggs',
      'Mixed salad leaves',
      'Olive oil + salt + pepper',
      'Optional: hot sauce or lemon drizzle',
    ],
    instructions: 'Sweet potato: pierce all over with a fork, microwave 6–8 min turning halfway until soft, or roast at 200°C for 35–40 min. Boiled eggs: place in cold water, bring to boil, cook 7 min for a firm yolk. Transfer to cold water before peeling. Slice sweet potato and arrange with salad leaves and halved eggs. Drizzle olive oil, season well.',
    tip: 'Prep the sweet potato before your shift starts — it reheats in 2 min in the microwave and still tastes great.',
  },
  {
    id: 'almond-rice-cake',
    name: 'Almond Butter Rice Cakes',
    emoji: '🌾',
    calories: 180,
    protein: 5,
    carbs: 22,
    fat: 9,
    timing: 'Pre-sleep light snack',
    category: 'snack',
    description: 'Light, easy to digest before sleep. Quick energy from the rice cakes, healthy fats from almond butter.',
    ingredients: [
      '2 plain rice cakes',
      '1 tbsp almond butter',
      'Optional: pinch of cinnamon or drizzle of honey',
    ],
    instructions: 'Spread almond butter evenly over rice cakes. Add a pinch of cinnamon or a light drizzle of honey if you want a touch of sweetness. No cooking needed — done in under a minute.',
    tip: 'Keep rice cakes and a jar of almond butter in your desk drawer. This takes 30 seconds and does the job.',
  },
  {
    id: 'banana-nuts',
    name: 'Banana & Mixed Nuts',
    emoji: '🍌',
    calories: 250,
    protein: 6,
    carbs: 34,
    fat: 12,
    timing: 'Mid-work snack',
    category: 'night-shift',
    description: 'Fast carbs from banana for a quick energy boost, healthy fats from nuts for sustained focus.',
    ingredients: [
      '1 ripe banana',
      '20–30g mixed nuts (almonds, cashews, walnuts)',
      'Optional: 1 tsp almond butter for dipping',
    ],
    instructions: 'No prep needed. Peel and eat. The banana provides quick carbs and the nuts slow the energy release so there\'s no crash. Optional: slice the banana and dip in almond butter.',
    tip: 'Pre-portion your nuts into a small container before your shift — it\'s easy to overeat them straight from the bag at 2 AM.',
  },
  {
    id: 'string-cheese-crackers',
    name: 'Cheese & Cracker Plate',
    emoji: '🧀',
    calories: 220,
    protein: 12,
    carbs: 24,
    fat: 9,
    timing: 'Mid-work snack',
    category: 'night-shift',
    description: 'A proper desk-friendly snack. Protein from cheese, complex carbs from wholegrains, sweetness from grapes.',
    ingredients: [
      '2 sticks string cheese (or 40g cheese)',
      '10 wholegrain crackers',
      'Handful of grapes',
    ],
    instructions: 'No prep needed. Arrange crackers on a plate or pack in a container. Pull string cheese apart or slice it. Add grapes on the side. Ready in seconds.',
    tip: 'Pack this into a container before your shift so it\'s ready to grab from the fridge at 2 AM without any effort.',
  },
  {
    id: 'mixed-nuts-choc',
    name: 'Nuts & Dark Chocolate',
    emoji: '🍫',
    calories: 240,
    protein: 6,
    carbs: 16,
    fat: 18,
    timing: 'Mid-work snack',
    category: 'night-shift',
    description: 'A satisfying late-night treat that\'s still macro-friendly. Dark chocolate has antioxidants and a little caffeine kick.',
    ingredients: [
      '30g mixed nuts (almonds, walnuts, cashews)',
      '20g dark chocolate (70%+)',
    ],
    instructions: 'No prep needed. Portion out nuts and break chocolate into squares. Eat together or alternate — the slight bitterness of dark chocolate pairs well with the richness of the nuts.',
    tip: 'Stick to 70%+ dark chocolate — less sugar, more cocoa. Pre-portion into a small container before your shift.',
  },
  {
    id: 'banana-pb',
    name: 'Banana & Peanut Butter',
    emoji: '🥜',
    calories: 240,
    protein: 6,
    carbs: 38,
    fat: 9,
    timing: 'Pre-work / light snack',
    category: 'snack',
    description: 'A quick, satisfying snack before work starts. Great vehicle for creatine on rest days.',
    ingredients: [
      '1 banana',
      '1–2 tbsp natural peanut butter',
    ],
    instructions: 'Peel and slice banana. Use peanut butter as a dip or spread over slices. Take creatine (5g) alongside on rest days — the banana\'s carbs help absorption.',
    tip: 'Natural peanut butter (ingredients: just peanuts) is the better choice. Stir the oil back in if it\'s separated at the top.',
  },
];

export const MACRO_TARGETS = {
  calories: 1900,
  protein: 145,
  carbs: 200,
  fat: 65,
  water: 2500, // ml
  note: 'Targets are approximate for a 30F toning goal at moderate activity level. Adjust based on hunger and progress.',
};
