import { StyleSheet } from 'react-native';
import { AppThemeType } from '@/constants/theme';

export function createIndexStyles(theme: AppThemeType) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    scroll: { flex: 1 },
    content: { paddingHorizontal: 16, paddingTop: 8 },

    targetsCard: { backgroundColor: theme.bgCard, borderRadius: 16, paddingHorizontal: 16, paddingTop: 8, paddingBottom: 4, borderWidth: 1, borderColor: theme.border, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
    targetRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10 },
    targetRowBorder: { borderBottomWidth: 1, borderBottomColor: theme.border },
    targetRowEmoji: { fontSize: 15, width: 22, textAlign: 'center' },
    targetRowLabel: { fontSize: 12, color: theme.textSecondary, width: 58 },
    targetRowBar: { flex: 1, height: 5, backgroundColor: theme.bgCardAlt, borderRadius: 3, overflow: 'hidden' },
    targetRowFill: { height: 6, borderRadius: 3 },
    targetRowValue: { fontSize: 12, fontWeight: '700', textAlign: 'right', minWidth: 42 },
    targetRowSep: { fontSize: 11, color: theme.textMuted, fontWeight: '400' },
    targetRowTotal: { fontSize: 11, color: theme.textMuted, fontWeight: '400' },

    section: { marginBottom: 20 },
    sectionTitle: { fontSize: 15, fontWeight: '700', color: theme.textPrimary, marginBottom: 10 },

    // Quick Log
    quickCard: { backgroundColor: theme.bgCard, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: theme.border, marginBottom: 20 },
    quickBtn: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 16, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: theme.border },
    quickBtnLast: { borderBottomWidth: 0 },
    quickBtnIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    quickBtnEmoji: { fontSize: 20 },
    quickBtnLabel: { fontSize: 16, fontWeight: '700', color: theme.textPrimary, flex: 1 },
    quickBtnChevron: { fontSize: 16, color: theme.textMuted },
    quickPanel: { paddingHorizontal: 16, paddingBottom: 16, gap: 10 },
    quickPanelDivider: { height: 1, backgroundColor: theme.border, marginBottom: 6 },
    waterPillRow: { flexDirection: 'row', gap: 8 },
    waterPill: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center', backgroundColor: theme.bgCardAlt, borderWidth: 1, borderColor: theme.border },
    waterPillText: { fontSize: 14, fontWeight: '700', color: theme.secondary },
    waterTotal: { fontSize: 12, color: theme.textMuted, textAlign: 'center', marginTop: 2 },
    waterSheetLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: -4 },
    waterTotalRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
    waterResetBtn: { fontSize: 13, fontWeight: '700' },
    quickInput: { backgroundColor: theme.bgCardAlt, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 11, fontSize: 15, color: theme.textPrimary, borderWidth: 1, borderColor: theme.border },
    quickInputRow: { flexDirection: 'row', gap: 8 },
    quickSubmitBtn: { borderRadius: 12, paddingVertical: 13, alignItems: 'center' },
    quickSubmitText: { fontSize: 15, fontWeight: '700', color: '#fff' },
    quickCaptureRow: { flexDirection: 'row', gap: 8 },
    quickCaptureBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 10, paddingVertical: 10, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.bgCardAlt },
    quickCaptureBtnText: { fontSize: 13, fontWeight: '600', color: theme.textSecondary },
    workoutDoneBox: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 4 },
    workoutDoneText: { fontSize: 14, fontWeight: '600', color: theme.success },
    // Camera modals
    camOverlay: { flex: 1, backgroundColor: '#000' },
    camClose: { position: 'absolute', top: 56, right: 20, backgroundColor: '#00000099', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
    camCloseText: { color: '#fff', fontWeight: '700', fontSize: 14 },
    camScanFrame: { position: 'absolute', top: '30%', left: '10%', right: '10%', height: 160, borderRadius: 16, borderWidth: 2, borderColor: '#fff' },
    camCornerTL: { position: 'absolute', top: -2, left: -2, width: 24, height: 24, borderTopWidth: 4, borderLeftWidth: 4, borderColor: theme.meal, borderTopLeftRadius: 14 },
    camCornerTR: { position: 'absolute', top: -2, right: -2, width: 24, height: 24, borderTopWidth: 4, borderRightWidth: 4, borderColor: theme.meal, borderTopRightRadius: 14 },
    camCornerBL: { position: 'absolute', bottom: -2, left: -2, width: 24, height: 24, borderBottomWidth: 4, borderLeftWidth: 4, borderColor: theme.meal, borderBottomLeftRadius: 14 },
    camCornerBR: { position: 'absolute', bottom: -2, right: -2, width: 24, height: 24, borderBottomWidth: 4, borderRightWidth: 4, borderColor: theme.meal, borderBottomRightRadius: 14 },
    camLabel: { position: 'absolute', top: '58%', left: 0, right: 0, textAlign: 'center', color: '#ffffffcc', fontSize: 14 },
    camCaptureBtn: { position: 'absolute', bottom: 60, alignSelf: 'center', width: 72, height: 72, borderRadius: 36, borderWidth: 4, borderColor: '#fff', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffffff22' },
    camCaptureDot: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#fff' },
    camHint: { position: 'absolute', bottom: 150, left: 0, right: 0, textAlign: 'center', color: '#ffffffcc', fontSize: 13 },
    camPermBox: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 32 },
    camPermText: { fontSize: 15, color: '#fff', textAlign: 'center', lineHeight: 22 },
    camPermBtn: { backgroundColor: theme.meal, borderRadius: 12, paddingHorizontal: 24, paddingVertical: 12 },
    camPermBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },

    checklistTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    checklistProgress: { fontSize: 13, fontWeight: '700', color: theme.primary },
    progressBg: { height: 4, backgroundColor: theme.bgCardAlt, borderRadius: 2, marginBottom: 12, overflow: 'hidden' },
    progressFill: { height: 4, backgroundColor: theme.primary, borderRadius: 2 },
    progressSkippedFill: { position: 'absolute', height: 4, borderRadius: 2, backgroundColor: '#f59e0b55' },
    allDone: { backgroundColor: theme.success + '22', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: theme.success + '44', marginBottom: 10 },
    allDoneText: { fontSize: 13, color: theme.success, textAlign: 'center', fontWeight: '600' },
    timeline: { paddingLeft: 2 },

    weekRow: { gap: 10, paddingRight: 16 },
    dayPill: { backgroundColor: theme.bgCard, borderRadius: 12, padding: 12, alignItems: 'center', minWidth: 68, borderWidth: 1, borderColor: theme.border },
    dayPillActive: { borderColor: theme.primary, backgroundColor: theme.primary + '15' },
    todayDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: theme.primary, marginBottom: 4 },
    dayPillName: { fontSize: 11, fontWeight: '700', color: theme.textSecondary, letterSpacing: 0.5, marginBottom: 2 },
    dayPillDate: { fontSize: 18, fontWeight: '800', color: theme.textPrimary, marginBottom: 6 },
    dayPillTypeDot: { width: 6, height: 6, borderRadius: 3 },

    heroCard: { borderRadius: 20, padding: 20, marginBottom: 20, overflow: 'hidden' },
    heroShine: { position: 'absolute', top: -30, left: -20, width: 160, height: 100, backgroundColor: '#ffffff18', borderRadius: 60, transform: [{ rotate: '-20deg' }] },
    heroTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 },
    heroGreeting: { fontSize: 13, fontWeight: '600', color: '#ffffff88', marginBottom: 4 },
    heroName: { fontSize: 22, fontWeight: '800', color: '#fff', marginBottom: 2 },
    heroMotivation: { fontSize: 13, color: '#ffffff77' },
    heroBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end', maxWidth: 140 },
    heroBadge: { backgroundColor: '#ffffff22', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 4 },
    heroBadgeText: { fontSize: 11, fontWeight: '700', color: '#ffffffdd' },
    heroDivider: { height: 1, backgroundColor: '#ffffff25', marginBottom: 14 },
    heroFocusLabel: { fontSize: 11, fontWeight: '700', color: '#ffffffaa', letterSpacing: 1.2, marginBottom: 4 },
    heroFocus: { fontSize: 15, fontWeight: '700', color: '#fff', marginBottom: 16 },
    heroBarRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    heroSegments: { flex: 1, flexDirection: 'row', gap: 4 },
    heroSegment: { flex: 1, height: 6, borderRadius: 3, backgroundColor: '#ffffff25' },
    heroSegmentFilled: { backgroundColor: '#fff', shadowColor: '#fff', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.9, shadowRadius: 5, elevation: 4 },
    heroPct: { fontSize: 13, fontWeight: '800', color: '#fff', minWidth: 36, textAlign: 'right' },

    backToTodayBtn: { alignSelf: 'flex-start', marginBottom: 12 },
    backToTodayText: { fontSize: 14, fontWeight: '700' },

    // Bottom sheet
    sheetScrim: { flex: 1, backgroundColor: '#00000055' },
    sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingBottom: 36, paddingTop: 12, gap: 12 },
    sheetHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 4 },
    sheetTitle: { fontSize: 18, fontWeight: '800', marginBottom: 4 },
    sheetBack: { alignSelf: 'flex-start', marginBottom: -4 },
    sheetBackText: { fontSize: 15, fontWeight: '600' },
    sheetRow: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 14, borderBottomWidth: 1 },
    sheetRowIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    sheetRowEmoji: { fontSize: 20 },
    sheetRowText: { flex: 1, gap: 2 },
    sheetRowLabel: { fontSize: 15, fontWeight: '600' },
    sheetRowSub: { fontSize: 12 },
    sheetRowChevron: { fontSize: 18 },

    // Hero progress bars
    heroProgressRows: { gap: 8 },
    heroProgressRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    heroProgressName: { fontSize: 11, fontWeight: '600', color: '#ffffffbb', width: 56 },
    heroProgressTrack: { flex: 1, height: 5, borderRadius: 3, backgroundColor: '#ffffff25', overflow: 'hidden' },
    heroProgressFill: { height: 5, borderRadius: 3, backgroundColor: '#fff' },
    heroProgressValue: { fontSize: 11, color: '#ffffffbb', fontWeight: '600', minWidth: 80, textAlign: 'right' },

    // Hydration widget
    hydrationCard:      { backgroundColor: theme.bgCard, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: theme.border, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
    hydrationHeader:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
    hydrationTitle:     { fontSize: 15, fontWeight: '700', color: theme.textPrimary },
    hydrationAmount:    { fontSize: 18, fontWeight: '800' },
    hydrationTarget:    { fontSize: 13, fontWeight: '400', color: theme.textMuted },
    hydrationBarBg:     { height: 8, backgroundColor: theme.bgCardAlt, borderRadius: 4, overflow: 'hidden', marginBottom: 14 },
    hydrationBarFill:   { height: 8, borderRadius: 4 },
    hydrationPills:     { flexDirection: 'row', gap: 8 },
    hydrationPill:      { flex: 1, paddingVertical: 10, borderRadius: 12, alignItems: 'center', borderWidth: 1 },
    hydrationPillText:  { fontSize: 13, fontWeight: '700' },
    hydrationReset:     { marginTop: 10, alignSelf: 'center' },
    hydrationResetText: { fontSize: 13, color: theme.textMuted, fontWeight: '700' },

    bottomPad: { height: 80 },
  });
}

export type IndexStyles = ReturnType<typeof createIndexStyles>;
