import { StyleSheet } from 'react-native';
import { AppThemeType } from '@/constants/theme';

export function createNutritionStyles(theme: AppThemeType) {
  return StyleSheet.create({
    safe:          { flex: 1, backgroundColor: theme.bg },
    scroll:        { flex: 1 },
    scrollContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 32 },

    // ── Header ───────────────────────────────────────────────────────────────
    header:   { marginBottom: 20 },
    title:    { fontSize: 26, fontWeight: '800', color: theme.textPrimary, letterSpacing: -0.3 },
    subtitle: { fontSize: 13, color: theme.textMuted, marginTop: 2 },

    // ── Hero card ─────────────────────────────────────────────────────────────
    // No backgroundColor — LinearGradient provides the background
    heroCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: 'rgba(168,85,247,0.25)',
      paddingTop: 28,
      paddingBottom: 24,
      paddingHorizontal: 20,
      alignItems: 'center',
      marginBottom: 14,
      overflow: 'hidden',
      shadowColor: '#a855f7',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 8,
    },
    heroScoreLabel: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 2,
      color: 'rgba(255,255,255,0.45)',
      marginBottom: 20,
      textTransform: 'uppercase',
    },
    heroScoreNum: {
      fontSize: 58,
      fontWeight: '900',
      lineHeight: 62,
      letterSpacing: -3,
    },
    heroScoreDenom: {
      fontSize: 15,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.4)',
      marginTop: 4,
    },
    heroQualityLabel: {
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 2.5,
      marginTop: 2,
      textTransform: 'uppercase',
    },
    heroMotivation: {
      fontSize: 13,
      color: 'rgba(255,255,255,0.65)',
      textAlign: 'center',
      marginTop: 20,
      lineHeight: 19,
      paddingHorizontal: 8,
    },

    // ── Week dot strip ────────────────────────────────────────────────────────
    weekStripCard: {
      backgroundColor: theme.bgCard,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 14,
    },
    weekStripHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    weekStripTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    weekStripCount: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    weekDotRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    weekDayCol: {
      alignItems: 'center',
      gap: 6,
    },
    weekDayLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textMuted,
      letterSpacing: 0.3,
    },
    weekDayLabelToday: {
      color: theme.primary,
    },
    weekDot: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    weekDotFull: {
      backgroundColor: theme.success,
      shadowColor: theme.success,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.55,
      shadowRadius: 6,
      elevation: 4,
    },
    weekDotPartial: {
      backgroundColor: theme.primary + '44',
      borderWidth: 2,
      borderColor: theme.primary,
    },
    weekDotMissed:  { backgroundColor: theme.bgCardAlt, borderWidth: 1.5, borderColor: theme.border },
    weekDotFuture:  { backgroundColor: theme.bgCardAlt, borderWidth: 1, borderColor: theme.border, opacity: 0.35 },
    weekDotToday: {
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.75,
      shadowRadius: 8,
      elevation: 6,
    },

    // ── Streak pills ──────────────────────────────────────────────────────────
    streakRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
    },
    // No backgroundColor — provided by LinearGradient
    streakPill: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 16,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 14,
      overflow: 'hidden',
    },
    streakEmoji:     { fontSize: 22 },
    streakTextCol:   { flex: 1 },
    streakCount:     { fontSize: 20, fontWeight: '900', lineHeight: 24 },
    streakLabel:     { fontSize: 11, color: theme.textMuted, marginTop: 1 },
    streakDaysLabel: { fontSize: 10, fontWeight: '700', color: theme.textMuted, marginLeft: 1 },

    // ── Period tabs ───────────────────────────────────────────────────────────
    periodTabRow: {
      flexDirection: 'row',
      backgroundColor: theme.bgCardAlt,
      borderRadius: 14,
      padding: 3,
      marginBottom: 14,
      gap: 2,
    },
    periodTab: {
      flex: 1,
      paddingVertical: 9,
      borderRadius: 11,
      alignItems: 'center',
      overflow: 'hidden',
    },
    // No backgroundColor — LinearGradient when active
    periodTabActive: {
      shadowColor: '#a855f7',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 3,
    },
    periodTabText:       { fontSize: 12, fontWeight: '600', color: theme.textMuted },
    periodTabTextActive: { color: '#fff', fontWeight: '700' },

    // ── Stats content card ────────────────────────────────────────────────────
    statsCard: {
      backgroundColor: theme.bgCard,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 8,
      marginBottom: 14,
    },
    statRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 10,
    },
    statEmoji:     { fontSize: 16, width: 24, textAlign: 'center' },
    statLabel:     { flex: 1, fontSize: 13, color: theme.textSecondary, fontWeight: '500' },
    statTrack:     { flex: 2, height: 8, backgroundColor: theme.bgCardAlt, borderRadius: 4, overflow: 'hidden' },
    statFill:      { height: 8, borderRadius: 4 },
    statValue:     { fontSize: 12, fontWeight: '700', color: theme.textPrimary, minWidth: 36, textAlign: 'right' },
    statDivider:   { height: 1, backgroundColor: theme.border + '55', marginBottom: 16 },
    statHighlight: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.bgCardAlt,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      marginBottom: 10,
    },
    statHighlightLabel: { fontSize: 12, color: theme.textSecondary },
    statHighlightValue: { fontSize: 14, fontWeight: '800', color: theme.textPrimary },
    compareBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 10,
      marginBottom: 14,
      alignSelf: 'flex-start',
    },
    compareBadgeText: { fontSize: 12, fontWeight: '700' },
    coachLine: {
      fontSize: 13,
      color: theme.textSecondary,
      fontStyle: 'italic',
      textAlign: 'center',
      paddingVertical: 4,
      paddingBottom: 10,
      lineHeight: 19,
    },
    todayStatusRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 10,
    },
    todayStatusPill: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 14,
      borderRadius: 14,
      gap: 5,
      overflow: 'hidden',
    },
    todayStatusEmoji:  { fontSize: 22 },
    todayStatusLabel:  { fontSize: 11, fontWeight: '600', color: theme.textSecondary },
    todayStatusValue:  { fontSize: 12, fontWeight: '700' },

    // ── Momentum chart ────────────────────────────────────────────────────────
    momentumCard: {
      backgroundColor: theme.bgCard,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 14,
      marginBottom: 14,
    },
    momentumHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 18,
    },
    momentumTitle:  { fontSize: 14, fontWeight: '700', color: theme.textPrimary },
    momentumTrend:  { fontSize: 12, fontWeight: '600' },
    momentumBars:   { flexDirection: 'row', alignItems: 'flex-end', gap: 5, height: 80 },
    momentumBarCol: { flex: 1, alignItems: 'center', gap: 4 },
    momentumTrack:  { width: '100%', backgroundColor: theme.bgCardAlt, borderRadius: 5, overflow: 'hidden', justifyContent: 'flex-end' },
    momentumFill:   { width: '100%', borderRadius: 5 },
    momentumLabel:  { fontSize: 8, color: theme.textMuted, fontWeight: '500', textAlign: 'center' },

    // ── Weight card ───────────────────────────────────────────────────────────
    carouselOuter: { marginBottom: 14 },
    carouselDots: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, paddingTop: 12 },
    carouselDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.border },
    carouselDotActive: { width: 20, height: 6, borderRadius: 3, backgroundColor: theme.primary },

    // Tab pills above the carousel
    carouselTabs: {
      flexDirection: 'row',
      backgroundColor: theme.bgCardAlt,
      borderRadius: 14,
      padding: 3,
      marginBottom: 10,
      gap: 2,
    },
    carouselTab: {
      flex: 1,
      paddingVertical: 9,
      borderRadius: 11,
      alignItems: 'center',
    },
    carouselTabActive: {
      backgroundColor: theme.primary,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 3,
    },
    carouselTabText:       { fontSize: 13, fontWeight: '600', color: theme.textMuted },
    carouselTabTextActive: { color: '#fff', fontWeight: '700' },

    // Shared card style for both carousel slides
    carouselCard: {
      flex: 1,
      backgroundColor: theme.bgCard,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },

    // Post-log coaching banner
    postLogBanner: {
      backgroundColor: theme.primary + '18',
      borderRadius: 10,
      padding: 14,
      borderLeftWidth: 3,
      borderLeftColor: theme.primary,
      marginBottom: 14,
    },
    postLogBannerText: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 20,
    },

    weightHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 12,
    },
    weightHeaderLeft: { flex: 1 },
    weightTitle:      { fontSize: 14, fontWeight: '700', color: theme.textPrimary },
    weightSubtitle:   { fontSize: 12, color: theme.textMuted, marginTop: 2 },
    weightExpandBtn:  { fontSize: 13, color: theme.textMuted, fontWeight: '600', paddingLeft: 8 },

    // Hero number section — sits between header and body
    weightHero: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 10,
      paddingHorizontal: 16,
      paddingBottom: 4,
    },
    weightHeroTrend: {
      fontSize: 12,
      color: theme.textMuted,
      paddingHorizontal: 16,
      paddingBottom: 14,
    },
    weightCurrent:  { fontSize: 32, fontWeight: '900', letterSpacing: -1 },
    weightDelta:    { fontSize: 13, fontWeight: '700' },

    // BMI hero — centered, prominent
    bmiHero: {
      alignItems: 'center',
      paddingVertical: 18,
      paddingHorizontal: 16,
    },
    bmiHeroNumber: {
      fontSize: 72,
      fontWeight: '900',
      letterSpacing: -4,
      lineHeight: 76,
    },
    bmiHeroLabel: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      marginTop: 6,
      opacity: 0.55,
    },

    weightBody: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 16,
      borderTopWidth: 1,
      borderTopColor: theme.border + '55',
    },
    weightInputRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
    weightInput: {
      flex: 1,
      backgroundColor: theme.bgCardAlt,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 16,
      color: theme.textPrimary,
      borderWidth: 1,
      borderColor: theme.border,
    },
    weightBtn:     { backgroundColor: theme.primary, borderRadius: 10, paddingHorizontal: 16, justifyContent: 'center' },
    weightBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    weightHistory: { marginTop: 14, borderTopWidth: 1, borderTopColor: theme.border, paddingTop: 12 },
    historyLabel:  { fontSize: 11, color: theme.textMuted, marginBottom: 8, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
    historyRow:    { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: theme.border + '55' },
    historyDate:   { fontSize: 13, color: theme.textSecondary },
    historyKg:     { fontSize: 13, fontWeight: '700', color: theme.textPrimary },
    historyHint:   { fontSize: 10, color: theme.textMuted, marginTop: 8, textAlign: 'center' },
    emptyText:     { fontSize: 13, color: theme.textMuted, textAlign: 'center', marginTop: 12, lineHeight: 20 },
    weightNudge: {
      backgroundColor: theme.primary + '15',
      borderRadius: 10,
      padding: 12,
      borderLeftWidth: 3,
      borderLeftColor: theme.primary,
      marginBottom: 14,
    },
    weightNudgeText: { fontSize: 13, color: theme.textSecondary, lineHeight: 20 },
    historyShowMore: { fontSize: 13, color: theme.primary, fontWeight: '600', textAlign: 'center', paddingVertical: 8 },

    bmiBadge:         { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
    bmiCategoryText:  { fontSize: 11, fontWeight: '700' },
    bmiScaleLabels:   { flexDirection: 'row', marginTop: 8, marginBottom: 14 },
    bmiScaleLabelText: { fontSize: 9, fontWeight: '700', textAlign: 'center', letterSpacing: 0.2 },
    bmiCoachBox: {
      borderRadius: 10,
      padding: 12,
      borderLeftWidth: 3,
      marginBottom: 10,
    },
    bmiCoachText:    { fontSize: 13, color: theme.textSecondary, lineHeight: 20 },
    bmiTip:     { backgroundColor: theme.primary + '18', borderRadius: 8, padding: 10, borderWidth: 1, borderColor: theme.primary + '40' },
    bmiTipText: { fontSize: 12, color: theme.primaryLight, lineHeight: 17 },

    // ── Steps card ────────────────────────────────────────────────────────────
    stepsHeader:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: theme.border + '55' },
    stepsHeaderLeft:  { gap: 2 },
    stepsTitle:       { fontSize: 14, fontWeight: '700', color: theme.textPrimary },
    stepsSubtitle:    { fontSize: 11, color: theme.textMuted },
    stepsConnectedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: theme.success + '22', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: theme.success + '55' },
    stepsConnectedDot:   { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.success },
    stepsConnectedText:  { fontSize: 10, fontWeight: '700', color: theme.success },

    stepsHero:        { alignItems: 'center', paddingVertical: 18, paddingHorizontal: 16 },
    stepsHeroNumber:  { fontSize: 64, fontWeight: '900', letterSpacing: -3, lineHeight: 68, color: theme.textPrimary },
    stepsHeroGoal:    { fontSize: 12, color: theme.textMuted, marginTop: 2 },

    stepsProgressTrack: { height: 6, backgroundColor: theme.bgCardAlt, borderRadius: 3, marginHorizontal: 16, marginBottom: 4, overflow: 'hidden' },
    stepsProgressFill:  { height: 6, borderRadius: 3 },
    stepsProgressLabel: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 16, marginBottom: 16 },
    stepsProgressPct:   { fontSize: 11, fontWeight: '700' },
    stepsProgressGoalText: { fontSize: 11, color: theme.textMuted },

    stepsBars:        { flexDirection: 'row', alignItems: 'flex-end', gap: 4, height: 52, paddingHorizontal: 16, marginBottom: 6 },
    stepsBarCol:      { flex: 1, alignItems: 'center', gap: 3 },
    stepsBarTrack:    { width: '100%', backgroundColor: theme.bgCardAlt, borderRadius: 3, overflow: 'hidden', justifyContent: 'flex-end' },
    stepsBarFill:     { width: '100%', borderRadius: 3 },
    stepsBarLabel:    { fontSize: 8, color: theme.textMuted, fontWeight: '500', textAlign: 'center' },

    stepsTip:         { backgroundColor: theme.primary + '18', borderRadius: 8, padding: 10, margin: 16, marginTop: 4, borderWidth: 1, borderColor: theme.primary + '40' },
    stepsTipText:     { fontSize: 12, color: theme.primaryLight, lineHeight: 17 },

    // Not-connected state
    stepsEmptyCard:   { flex: 1, padding: 20, justifyContent: 'center' },
    stepsEmptyIcon:   { fontSize: 36, textAlign: 'center', marginBottom: 12 },
    stepsEmptyTitle:  { fontSize: 16, fontWeight: '800', color: theme.textPrimary, textAlign: 'center', marginBottom: 6 },
    stepsEmptyBody:   { fontSize: 13, color: theme.textSecondary, textAlign: 'center', lineHeight: 20, marginBottom: 20 },
    stepsConnectBtn:  { backgroundColor: theme.primary, borderRadius: 12, paddingVertical: 13, alignItems: 'center', marginBottom: 24 },
    stepsConnectBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },

    // Steps bottom sheet
    stepsSheetScrim:  { flex: 1, backgroundColor: '#00000055' },
    stepsSheet:       { borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingBottom: 40, paddingTop: 12, backgroundColor: theme.bgCard },
    stepsSheetHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 16, backgroundColor: theme.border },
    stepsSheetTitle:  { fontSize: 18, fontWeight: '800', color: theme.textPrimary, marginBottom: 4 },
    stepsSheetSub:    { fontSize: 13, color: theme.textSecondary, lineHeight: 20, marginBottom: 20 },
    stepsSheetRow:    { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: theme.border },
    stepsSheetIcon:   { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
    stepsSheetIconEmoji: { fontSize: 20 },
    stepsSheetRowText:  { flex: 1 },
    stepsSheetRowLabel: { fontSize: 15, fontWeight: '600', color: theme.textPrimary, marginBottom: 2 },
    stepsSheetRowSub:   { fontSize: 12, color: theme.textSecondary },
    stepsSheetChevron:  { fontSize: 18, color: theme.textMuted },
    stepsSheetSoonLabel: { fontSize: 10, fontWeight: '700', color: theme.textMuted, textTransform: 'uppercase', letterSpacing: 0.8, marginTop: 20, marginBottom: 10 },
    stepsSheetSoonGrid:  { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    stepsSheetSoonPill:  { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.bgCardAlt },
    stepsSheetSoonPillText: { fontSize: 12, fontWeight: '600', color: theme.textSecondary },
    stepsSheetSoonPillBadge: { fontSize: 9, fontWeight: '700', color: theme.textMuted },
    stepsSheetBack:    { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 16 },
    stepsSheetBackText: { fontSize: 15, fontWeight: '600', color: theme.primary },
    stepsSheetInput:   { backgroundColor: theme.bgCardAlt, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 32, fontWeight: '800', color: theme.textPrimary, textAlign: 'center', borderWidth: 1, borderColor: theme.border, marginBottom: 16 },
    stepsSheetSaveBtn: { backgroundColor: theme.primary, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
    stepsSheetSaveBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },

    // ── Coach Insights ────────────────────────────────────────────────────────
    coachSection:        { marginBottom: 4 },
    coachSectionTitle:   { fontSize: 11, fontWeight: '800', color: theme.textMuted, letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 10 },
    coachInsightCard:    { backgroundColor: theme.bgCard, borderRadius: 14, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderWidth: 1, borderColor: theme.border },
    coachInsightIconWrap:{ width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    coachInsightEmoji:   { fontSize: 18 },
    coachInsightBody:    { flex: 1, gap: 3 },
    coachInsightTitle:   { fontSize: 13, fontWeight: '700', color: theme.textPrimary },
    coachInsightText:    { fontSize: 13, color: theme.textSecondary, lineHeight: 19 },
  });
}

export type NutritionStyles = ReturnType<typeof createNutritionStyles>;
